version: "3.7"
services:
  stock:
    image: postgres:latest
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=univer
      - SSLMODE=false